# Conexão com o banco
spring.datasource.url=jdbc:mysql://localhost:3306/raphabarber?createDatabaseIfNotExist=true
spring.datasource.username=raphauser
spring.datasource.password=rapha1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Linha de segurança
api.security.token.secret=${JWT_SECRET:SuaSenhaSuperSecretaComMaisDe32CaracteresAqui}

# Mostrar o que o Spring está fazendo no banco (bom para aprender!)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

app.admin.email=rapha@barbearia.com
app.admin.password=admin123