# Conexão com o banco
spring.datasource.url=jdbc:mysql://localhost:3306/raphabarber_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=11092004

# Mostrar o que o Spring está fazendo no banco (bom para aprender!)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update